import math
import re
from typing import Dict, Any, Optional

def compute_sequence_entropy(
    response_metadata: Dict[str, Any],
    fallback_text: Optional[str] = None
) -> float:
    """
    Computes sequence-level Shannon Entropy across token log-probability distributions.
    
    H = -1/|L| * sum_t(sum_i(p_i * log(p_i)))
    
    If the metadata structure is incomplete or missing logprob keys (black-box fallback), 
    parses raw confidence patterns or defaults to a neutral entropy score.
    
    Args:
        response_metadata: Dict containing raw ChatOpenAI response metadata.
        fallback_text: Text generated by the LLM (for linguistic fallback parsing).
        
    Returns:
        float: Computed or proxy Shannon Entropy value.
    """
    try:
        # Check for standard OpenAI/vLLM logprobs structure
        if response_metadata and "logprobs" in response_metadata:
            logprobs_root = response_metadata["logprobs"]
            # Check vLLM / OpenAI JSON structure
            content = logprobs_root.get("content") if logprobs_root else None
            
            if content and isinstance(content, list):
                total_entropy = 0.0
                valid_tokens = 0
                
                for token_info in content:
                    top_logprobs = token_info.get("top_logprobs", [])
                    if not top_logprobs:
                        # Fallback to single logprob token if available
                        single_lp = token_info.get("logprob", None)
                        if single_lp is not None:
                            valid_tokens += 1
                        continue
                        
                    # Calculate position probability vector
                    probabilities = []
                    for opt in top_logprobs:
                        lp = opt.get("logprob", None)
                        if lp is not None:
                            probabilities.append(math.exp(lp))
                            
                    # Normalization pass to verify sum(p) == 1.0
                    sum_p = sum(probabilities)
                    if sum_p > 0:
                        norm_p = [p / sum_p for p in probabilities]
                        pos_entropy = -sum(p * math.log(p) for p in norm_p if p > 0)
                        total_entropy += pos_entropy
                        valid_tokens += 1
                        
                if valid_tokens > 0:
                    return float(total_entropy / valid_tokens)
    except Exception as e:
        print(f"[Entropy Computation Exception] Falling back to text heuristics: {e}")

    # Dual Fallback Layer: Parse verbalized metrics if logprobs are absent
    if fallback_text:
        try:
            # Look for structured confidence indicators in the text (e.g. "Confidence: 85%")
            pct_matches = re.findall(r'confidence\s*:\s*(\d{1,3})%', fallback_text.lower())
            if pct_matches:
                conf = float(pct_matches[-1]) / 100.0
            else:
                float_matches = re.findall(r'confidence\s*:\s*(0\.\d+|1\.0)', fallback_text.lower())
                if float_matches:
                    conf = float(float_matches[-1])
                else:
                    conf = 0.75  # Default calibration baseline
            
            conf = max(0.01, min(0.99, conf))
            # Calculate binary Shannon entropy proxy
            binary_entropy = -(conf * math.log(conf) + (1.0 - conf) * math.log(1.0 - conf))
            return float(binary_entropy)
        except Exception:
            return 0.5
            
    return 0.5